name: CI-CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      server_ip: ${{ steps.terraform-apply.outputs.server_ip }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "us-east-2"

      - name: Read destroy configuration
        id: read-destroy-config
        run: |
          DESTROY="$(jq -r '.prod' ./terraform/destroy_config.json)"
          echo "destroy=$(echo $DESTROY)" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: |
          terraform -chdir=terraform init \
            -backend-config="bucket=${{ secrets.BUCKET_SECRET }}" \
            -backend-config="key=${{ github.event.repository.name }}" \
            -backend-config="region=us-east-2" \
            -backend-config="dynamodb_table=${{ secrets.DYNAMODB }}"

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Destroy
        if: steps.read-destroy-config.outputs.destroy == 'true'
        id: terraform-destroy
        run: |
          terraform -chdir=terraform workspace select prod || terraform -chdir=terraform workspace new prod
          terraform -chdir=terraform destroy -var-file="./envs/prod/terraform.tfvars" -auto-approve

      - name: Terraform Plan
        if: steps.read-destroy-config.outputs.destroy != 'true'
        id: terraform-plan
        run: |
          terraform -chdir=terraform workspace select prod || terraform -chdir=terraform workspace new prod
          terraform -chdir=terraform plan -var-file="./envs/prod/terraform.tfvars" -out="prod.plan"

      - name: Terraform Apply
        if: steps.read-destroy-config.outputs.destroy != 'true'
        id: terraform-apply
        run: |
          terraform -chdir=terraform workspace select prod || terraform -chdir=terraform workspace new prod
          terraform -chdir=terraform apply -auto-approve "prod.plan"
          echo "server_ip=$(terraform -chdir=terraform output -raw public_ip)" >> $GITHUB_OUTPUT

  build:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Run tests
        run: |
          chmod +x ./test.sh
          ./test.sh

      - name: Generate tag
        id: tag
        run: echo "sha=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devopps:${{ steps.tag.outputs.sha }} ./app

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devopps:${{ steps.tag.outputs.sha }}

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/devoops_api
            git pull
            
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            export TAG=${{ steps.tag.outputs.sha }}

            echo "USANDO IMAGEM: $DOCKERHUB_USERNAME/devopps:$TAG"

            docker login -u $DOCKERHUB_USERNAME -p ${{ secrets.DOCKERHUB_TOKEN }}

            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            docker system prune -af
