name: CI-CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # -----------------------
      # CHECKOUT
      # -----------------------
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------
      # PYTHON
      # -----------------------
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      # -----------------------
      # TESTES
      # -----------------------
      - name: Run tests
        run: |
          chmod +x ./test.sh
          ./test.sh

      # -----------------------
      # SHA TAG
      # -----------------------
      - name: Generate tag
        id: tag
        run: |
          echo "sha=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT

      # -----------------------
      # LOGIN DOCKER HUB
      # -----------------------
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DEV0OPS }}

      # -----------------------
      # BUILD DA IMAGEM
      # -----------------------
      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/DEVOPPS:${{ steps.tag.outputs.sha }} ./app

      # -----------------------
      # PUSH PARA DOCKER HUB
      # -----------------------
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/DEVOPPS:${{ steps.tag.outputs.sha }}

      # -----------------------
      # DEPLOY AUTOMÁTICO NO SERVIDOR
      # -----------------------
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/devoops_api

            # Puxa últimas alterações do repositório
            git pull

            # Exporta TAG para o compose
            export TAG=${{ steps.tag.outputs.sha }}

            # Atualiza imagem
            docker compose -f docker-compose.prod.yml pull 

            # Sobe serviços com rebuild
            docker compose -f docker-compose.prod.yml up -d --build
